# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /
title: James Wen
author: James Wen
description: Personal blog and resume
avatar: headshot.jpg
email: jrw2175@columbia.edu
github: RochesterinNYC
twitter: RochesterinNYC
linkedin: jamesrwen
google_analytics: UA-35915936-6
